use customer_behavior;
select Top 20* from df_customers;

--Q1. What is the total revenue generated by male vs female customer ?
select gender, sum(purchase_amount) from df_customers
		group by gender;

--Q2. Which customer used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount from df_customers
			where discount_applied ='Yes' 
			and purchase_amount >= (select avg(purchase_amount) from df_customers);

--Q3. Which are the top 5 products with the highest average revew rating?
select Top 5 item_purchased, round(avg(review_rating),2) as 'Average Rating' from
		df_customers 
		group by item_purchased
		order by avg(review_rating) desc;

--Q4. Compare the average Purchase Amount between Standard and Express Shipping.
select shipping_type, avg(purchase_amount) 
		from df_customers
		where shipping_type in ('Standard','Express')
		group by shipping_type;

--Q5. Do Subscribed customer spend more? Compare average spend and total revenue between subscribed and non-subscribers.
select subscription_status,count(customer_id) as total_customer,
		ROUND(avg(purchase_amount),2) as avg_spend,
		round(sum(purchase_amount),2) as total_revenue
		from df_customers
		group by subscription_status;

--Q6. Which 5 Products have the highest percentage of Purchases with discount applied?
select top 5 item_purchased,
		round(100*sum(case when discount_applied ='Yes' then 1 else 0 end)/count(*),2) as discount_rate
		from df_customers
		group by item_purchased
		order by discount_rate desc;

--Q7. Segment Customer into new,Returning, and Loyal based on their total number of previous, and show the count each segment.
with cte as 
			(select customer_id, previous_purchases,
						case when previous_purchases = 1 then 'New'
							 When previous_purchases between 2 and 10 then 'Returning'
									else 'Loyal'
									end as Customer_Segment
						from df_customers)
 Select Customer_Segment, count(*) as 'Number_of_Customer'
		from cte
		group by Customer_Segment;

--Q8. What are the top 3 most purchased Products within each Category.
with cte as 
			(select category,item_purchased,count(customer_id) as total_orders,
					ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rnk
					from df_customers
					group by category,item_purchased)

	select category, item_purchased, total_orders
			from cte 
			where item_rnk <=3

--Q.9 Are Customer who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
	select subscription_status, count(customer_id) as repeat_buyers
			from df_customers
			where previous_purchases > 5
			group by subscription_status;

--Q.10 What id the revenue contribution of each age group?
select age_group, sum(purchase_amount) as revenue 
			from df_customers
			group by age_group
			order by revenue desc;
